[pytest]
markers =
    iam: IAM authentication and token lifecycle tests
    rest: REST API tests
rp_endpoint = http://host.docker.internal:8080
rp_project = superadmin_personal
rp_launch = Trading QA IAM API Demo
rp_launch_attributes = 'Pytest' 'IAM' 'API' 'Environment:local'
rp_log_level = INFO
rp_is_skipped_an_issue = False
